id: P004175
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 2021-12-17 10:58:24.345840
source_metadata:
  id: bdr:W25200
  title: སྒྲོལ་མའི་ལས་དབང
  author: ''
  volumes:
    ebd2e8cbe64f40bea3c412dbe05f4b36:
      image_group_id: I1KG5140
      title: ''
      volume_number: 1
      total_pages: 150
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
